### ISSUE TITLE
Playback stops at end of a track, does not continue with next track

### ISSUE THREAD

**Issue by gardiner** [jxnblk/SoundRad#21]
Every now and then SoundRad stops the playback at the end of a song and does not continue with the next song in the playlist. Interestingly, the official soundcloud website suffers the same problem. I have yet to confirm if this occurs with specific tracks.

Anyway, great player, _way_ better than the official website! Thanks!

**Comment by jxnblk** [comment]
Yeah, I've run into this. Not sure what causes it, but feel free to ping me if you notice any patterns.
