### ISSUE TITLE
Likes, playlist, and user pages not loading in Chrome

### ISSUE THREAD

**Issue by mrzool** [jxnblk/SoundRad#49]
Looks like SoundRad has trouble fetching the data.

The main stream looks OK though.

**Comment by jxnblk** [comment]
Are you still seeing issues? Not sure if I can reproduce. Also what browser are you using?

**Comment by mrzool** [comment]
Ok, I've just tested it, looks like the issue is only on Chrome, Safari works fine both on iOS and OS X.

**Comment by jxnblk** [comment]
Usually I encounter issues with safari.

Have you tried logging out and back in?

**Comment by mrzool** [comment]
Unfortunately I'm unable to do that on Chrome as the user page, where the Sign Out link resides, has also trouble loading. Same for the playlist page. I didn't notice that before. Seems like the only page loading properly on Chrome is the one containing the main stream.

Also, I've been seeing this issue for some time and on different computers so I don't think a login/logout would solve anything.

**Comment by jxnblk** [comment]
I'm not entirely sure what's happening, but I have see similar issues before that were resolved by clearing SoundRad's localStorage and logging out of soundcloud.com, then signing into both again.

If you want to try that, you can manually remove the localStorage, by opening web inspector and going to the resources tab, clicking on Local Storage, and removing `currentUser` and `token`.
![screenshot 2015-06-15 12 03 29](https://cloud.githubusercontent.com/assets/3451712/8164420/f9e7fd16-1356-11e5-9006-6309f8161aa6.png)

**Comment by mrzool** [comment]
That fixed it completely, I've got my likes back :)

Thanks a lot!

**Comment by jxnblk** [comment]
😎
